/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Sync
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twilio.rest.sync.v1.service;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.twilio.base.Resource;
import com.twilio.base.Resource;
import com.twilio.exception.ApiConnectionException;
import com.twilio.exception.ApiException;
import com.twilio.type.*;
import java.io.IOException;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.time.ZonedDateTime;
import java.util.Map;
import java.util.Objects;
import lombok.Getter;
import lombok.ToString;

@JsonIgnoreProperties(ignoreUnknown = true)
@ToString
public class SyncStream extends Resource {

    public static SyncStreamCreator creator(final String pathServiceSid) {
        return new SyncStreamCreator(pathServiceSid);
    }

    public static SyncStreamDeleter deleter(
        final String pathServiceSid,
        final String pathSid
    ) {
        return new SyncStreamDeleter(pathServiceSid, pathSid);
    }

    public static SyncStreamFetcher fetcher(
        final String pathServiceSid,
        final String pathSid
    ) {
        return new SyncStreamFetcher(pathServiceSid, pathSid);
    }

    public static SyncStreamReader reader(final String pathServiceSid) {
        return new SyncStreamReader(pathServiceSid);
    }

    public static SyncStreamUpdater updater(
        final String pathServiceSid,
        final String pathSid
    ) {
        return new SyncStreamUpdater(pathServiceSid, pathSid);
    }

    /**
     * Converts a JSON String into a SyncStream object using the provided ObjectMapper.
     *
     * @param json Raw JSON String
     * @param objectMapper Jackson ObjectMapper
     * @return SyncStream object represented by the provided JSON
     */
    public static SyncStream fromJson(
        final String json,
        final ObjectMapper objectMapper
    ) {
        // Convert all checked exceptions to Runtime
        try {
            return objectMapper.readValue(json, SyncStream.class);
        } catch (final JsonMappingException | JsonParseException e) {
            throw new ApiException(e.getMessage(), e);
        } catch (final IOException e) {
            throw new ApiConnectionException(e.getMessage(), e);
        }
    }

    /**
     * Converts a JSON InputStream into a SyncStream object using the provided
     * ObjectMapper.
     *
     * @param json Raw JSON InputStream
     * @param objectMapper Jackson ObjectMapper
     * @return SyncStream object represented by the provided JSON
     */
    public static SyncStream fromJson(
        final InputStream json,
        final ObjectMapper objectMapper
    ) {
        // Convert all checked exceptions to Runtime
        try {
            return objectMapper.readValue(json, SyncStream.class);
        } catch (final JsonMappingException | JsonParseException e) {
            throw new ApiException(e.getMessage(), e);
        } catch (final IOException e) {
            throw new ApiConnectionException(e.getMessage(), e);
        }
    }

    public static String toJson(Object object, ObjectMapper mapper) {
        try {
            return mapper.writeValueAsString(object);
        } catch (final JsonMappingException e) {
            throw new ApiException(e.getMessage(), e);
        } catch (JsonProcessingException e) {
            throw new ApiException(e.getMessage(), e);
        } catch (final IOException e) {
            throw new ApiConnectionException(e.getMessage(), e);
        }
    }

    @Getter
    private final String accountSid;

    @Getter
    private final String createdBy;

    @Getter
    private final ZonedDateTime dateCreated;

    @Getter
    private final ZonedDateTime dateExpires;

    @Getter
    private final ZonedDateTime dateUpdated;

    @Getter
    private final Map<String, String> links;

    @Getter
    private final String serviceSid;

    @Getter
    private final String sid;

    @Getter
    private final String uniqueName;

    @Getter
    private final URI url;

    @JsonCreator
    private SyncStream(
        @JsonProperty("account_sid") final String accountSid,
        @JsonProperty("created_by") final String createdBy,
        @JsonProperty("date_created") @JsonDeserialize(
            using = com.twilio.converter.ISO8601Deserializer.class
        ) final ZonedDateTime dateCreated,
        @JsonProperty("date_expires") @JsonDeserialize(
            using = com.twilio.converter.ISO8601Deserializer.class
        ) final ZonedDateTime dateExpires,
        @JsonProperty("date_updated") @JsonDeserialize(
            using = com.twilio.converter.ISO8601Deserializer.class
        ) final ZonedDateTime dateUpdated,
        @JsonProperty("links") final Map<String, String> links,
        @JsonProperty("service_sid") final String serviceSid,
        @JsonProperty("sid") final String sid,
        @JsonProperty("unique_name") final String uniqueName,
        @JsonProperty("url") final URI url
    ) {
        this.accountSid = accountSid;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
        this.dateExpires = dateExpires;
        this.dateUpdated = dateUpdated;
        this.links = links;
        this.serviceSid = serviceSid;
        this.sid = sid;
        this.uniqueName = uniqueName;
        this.url = url;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }

        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        SyncStream other = (SyncStream) o;
        return (
            Objects.equals(accountSid, other.accountSid) &&
            Objects.equals(createdBy, other.createdBy) &&
            Objects.equals(dateCreated, other.dateCreated) &&
            Objects.equals(dateExpires, other.dateExpires) &&
            Objects.equals(dateUpdated, other.dateUpdated) &&
            Objects.equals(links, other.links) &&
            Objects.equals(serviceSid, other.serviceSid) &&
            Objects.equals(sid, other.sid) &&
            Objects.equals(uniqueName, other.uniqueName) &&
            Objects.equals(url, other.url)
        );
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            accountSid,
            createdBy,
            dateCreated,
            dateExpires,
            dateUpdated,
            links,
            serviceSid,
            sid,
            uniqueName,
            url
        );
    }
}
