/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */

package com.twilio.twiml.voice;

import com.twilio.http.HttpMethod;
import org.junit.Assert;
import org.junit.Test;

import java.net.URI;

/**
 * Test class for {@link Enqueue}
 */
public class EnqueueTest {
    @Test
    public void testEmptyElement() {
        Enqueue elem = new Enqueue.Builder().build();

        Assert.assertEquals(
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
            "<Enqueue/>",
            elem.toXml()
        );
    }

    @Test
    public void testEmptyElementUrl() {
        Enqueue elem = new Enqueue.Builder().build();

        Assert.assertEquals("%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%3CEnqueue%2F%3E", elem.toUrl());
    }

    @Test
    public void testElementWithParams() {
        Enqueue elem = new Enqueue.Builder("name")
            .action(URI.create("https://example.com"))
            .method(HttpMethod.GET)
            .waitUrl(URI.create("https://example.com"))
            .waitUrlMethod(HttpMethod.GET)
            .workflowSid("workflow_sid")
            .build();

        Assert.assertEquals(
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
            "<Enqueue action=\"https://example.com\" method=\"GET\" waitUrl=\"https://example.com\" waitUrlMethod=\"GET\" workflowSid=\"workflow_sid\">name</Enqueue>",
            elem.toXml()
        );
    }

    @Test
    public void testElementWithExtraAttributes() {
        Enqueue elem = new Enqueue.Builder().option("foo", "bar").option("a", "b").build();

        Assert.assertEquals(
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
            "<Enqueue a=\"b\" foo=\"bar\"/>",
            elem.toXml()
        );
    }

    @Test
    public void testElementWithChildren() {
        Enqueue.Builder builder = new Enqueue.Builder();

        builder.task(new Task.Builder("body").priority(1).timeout(1).build());

        Enqueue elem = builder.build();

        Assert.assertEquals(
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
            "<Enqueue>" +
                "<Task priority=\"1\" timeout=\"1\">body</Task>" +
            "</Enqueue>",
            elem.toXml()
        );
    }
}