/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio Conversational Intelligence API
 * The Conversational Intelligence API includes resources to create and manage intelligence configurations, define and run language operators, and retrieve processed conversations and operator results.  * Use the Configurations resource to create and manage intelligence configurations and define rules that control how and when language operators analyze and transform conversations.  * Use the Operators resource to create custom language operators or retrieve Twilio-author and custom operators. * Use the Conversations resource to retrieve conversations processed with an intelligence configuration, and the OperatorResults resource to retrieve language operator results for those conversations.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twilio.rest.intelligence.v3;

import com.twilio.base.Page;
import com.twilio.base.Reader;
import com.twilio.base.ResourceSet;
import com.twilio.base.ResourceSetResponse;
import com.twilio.base.TokenPaginationPage;
import com.twilio.base.TwilioResponse;
import com.twilio.constant.EnumConstants.ParameterType;
import com.twilio.converter.Serializer;
import com.twilio.exception.ApiConnectionException;
import com.twilio.exception.ApiException;
import com.twilio.exception.RestException;
import com.twilio.exception.RestStandardException;
import com.twilio.http.HttpMethod;
import com.twilio.http.HttpUtility;
import com.twilio.http.Request;
import com.twilio.http.Response;
import com.twilio.http.TwilioRestClient;
import com.twilio.rest.Domains;
import com.twilio.type.*;
import java.io.InputStream;

public class ConfigurationReader
    extends Reader<Configuration.ListConfigurationResponse> {

    private Integer pageSize;
    private String pageToken;

    public ConfigurationReader() {}

    public ConfigurationReader setPageSize(final Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    public ConfigurationReader setPageToken(final String pageToken) {
        this.pageToken = pageToken;
        return this;
    }

    public ResourceSetResponse<
        Configuration.ListConfigurationResponse
    > readWithResponse(final TwilioRestClient client) {
        Request request = buildFirstPageRequest(client);
        Response response = makeRequest(client, request);
        Page<Configuration.ListConfigurationResponse> page = Page.fromJson(
            "items",
            response.getContent(),
            Configuration.ListConfigurationResponse.class,
            client.getObjectMapper()
        );
        ResourceSet<Configuration.ListConfigurationResponse> resourceSet =
            new ResourceSet<>(this, client, page);
        return new ResourceSetResponse<>(
            resourceSet,
            response.getStatusCode(),
            response.getHeaders()
        );
    }

    private Request buildFirstPageRequest(final TwilioRestClient client) {
        String path = "/v3/ControlPlane/Configurations";

        Request request = new Request(
            HttpMethod.GET,
            Domains.INTELLIGENCE.toString(),
            path
        );
        addQueryParams(request);
        return request;
    }

    @Override
    public ResourceSet<Configuration.ListConfigurationResponse> read(
        final TwilioRestClient client
    ) {
        return new ResourceSet<>(this, client, firstPage(client));
    }

    public Page<Configuration.ListConfigurationResponse> firstPage(
        final TwilioRestClient client
    ) {
        Request request = buildFirstPageRequest(client);
        return pageForRequest(client, request);
    }

    public TwilioResponse<
        Page<Configuration.ListConfigurationResponse>
    > firstPageWithResponse(final TwilioRestClient client) {
        Request request = buildFirstPageRequest(client);
        Response response = makeRequest(client, request);
        Page<Configuration.ListConfigurationResponse> page = Page.fromJson(
            "items",
            response.getContent(),
            Configuration.ListConfigurationResponse.class,
            client.getObjectMapper()
        );
        return new TwilioResponse<>(
            page,
            response.getStatusCode(),
            response.getHeaders()
        );
    }

    private Response makeRequest(
        final TwilioRestClient client,
        final Request request
    ) {
        Response response = client.request(request);
        if (response == null) {
            throw new ApiConnectionException(
                "Configuration read failed: Unable to connect to server"
            );
        } else if (!TwilioRestClient.SUCCESS.test(response.getStatusCode())) {
            InputStream inputStream = response.getStream();
            RestStandardException standardException =
                RestStandardException.fromJson(
                    inputStream,
                    client.getObjectMapper()
                );
            if (
                standardException != null && standardException.getType() != null
            ) {
                throw new ApiException(standardException);
            }
            RestException restException = RestException.fromJson(
                inputStream,
                client.getObjectMapper()
            );

            if (restException == null) {
                throw new ApiException(
                    "Server Error, no content",
                    response.getStatusCode()
                );
            }
            throw new ApiException(restException);
        }
        return response;
    }

    private Page<Configuration.ListConfigurationResponse> pageForRequest(
        final TwilioRestClient client,
        final Request request
    ) {
        Response response = makeRequest(client, request);
        return TokenPaginationPage.fromJson(
            "items",
            response.getContent(),
            Configuration.ListConfigurationResponse.class,
            client.getObjectMapper()
        );
    }

    @Override
    public Page<Configuration.ListConfigurationResponse> previousPage(
        final Page<Configuration.ListConfigurationResponse> page,
        final TwilioRestClient client
    ) {
        String path = "/v3/ControlPlane/Configurations";

        path = path + page.previousQueryString();
        Request request = new Request(
            HttpMethod.GET,
            Domains.INTELLIGENCE.toString(),
            path
        );

        return pageForRequest(client, request);
    }

    @Override
    public Page<Configuration.ListConfigurationResponse> nextPage(
        final Page<Configuration.ListConfigurationResponse> page,
        final TwilioRestClient client
    ) {
        String path = "/v3/ControlPlane/Configurations";

        path = path + page.nextQueryString();
        Request request = new Request(
            HttpMethod.GET,
            Domains.INTELLIGENCE.toString(),
            path
        );

        return pageForRequest(client, request);
    }

    @Override
    public Page<Configuration.ListConfigurationResponse> getPage(
        final String targetUrl,
        final TwilioRestClient client
    ) {
        if (!com.twilio.http.HttpUtility.isValidTwilioUrl(targetUrl)) {
            throw new ApiException(
                "Invalid URL: URL must be a valid Twilio domain"
            );
        }
        Request request = new Request(HttpMethod.GET, targetUrl);
        return pageForRequest(client, request);
    }

    private void addQueryParams(final Request request) {
        if (pageSize != null) {
            Serializer.toString(
                request,
                "pageSize",
                pageSize,
                ParameterType.QUERY
            );
        }

        if (pageToken != null) {
            Serializer.toString(
                request,
                "pageToken",
                pageToken,
                ParameterType.QUERY
            );
        }

        if (getPageSize() != null) {
            request.addQueryParam("PageSize", Integer.toString(getPageSize()));
        }
    }
}
