/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Api
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twilio.rest.api.v2010.account.sip.credentiallist;

import com.twilio.base.Fetcher;
import com.twilio.exception.ApiConnectionException;
import com.twilio.exception.ApiException;
import com.twilio.exception.RestException;
import com.twilio.http.HttpMethod;
import com.twilio.http.Request;
import com.twilio.http.Response;
import com.twilio.http.TwilioRestClient;
import com.twilio.rest.Domains;

public class CredentialFetcher extends Fetcher<Credential> {

    private String pathaccountSid;
    private String pathcredentialListSid;
    private String pathsid;

    public CredentialFetcher(final String pathcredentialListSid, final String pathsid) {
        this.pathcredentialListSid = pathcredentialListSid;
        this.pathsid = pathsid;
    }

    public CredentialFetcher(final String pathaccountSid, final String pathcredentialListSid, final String pathsid) {
        this.pathaccountSid = pathaccountSid;
        this.pathcredentialListSid = pathcredentialListSid;
        this.pathsid = pathsid;
    }


    @Override
    public Credential fetch(final TwilioRestClient client) {

        String path = "/2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists/{CredentialListSid}/Credentials/{Sid}.json";

        this.pathaccountSid = this.pathaccountSid == null ? client.getAccountSid() : this.pathaccountSid;
        path = path.replace("{" + "AccountSid" + "}", this.pathaccountSid.toString());
        path = path.replace("{" + "CredentialListSid" + "}", this.pathcredentialListSid.toString());
        path = path.replace("{" + "Sid" + "}", this.pathsid.toString());


        Request request = new Request(
                HttpMethod.GET,
                Domains.API.toString(),
                path
        );

        Response response = client.request(request);

        if (response == null) {
            throw new ApiConnectionException("Credential fetch failed: Unable to connect to server");
        } else if (!TwilioRestClient.SUCCESS.test(response.getStatusCode())) {
            RestException restException = RestException.fromJson(
                    response.getStream(),
                    client.getObjectMapper()
            );
            if (restException == null) {
                throw new ApiException("Server Error, no content", response.getStatusCode());
            }
            throw new ApiException(restException);
        }
        return Credential.fromJson(response.getStream(), client.getObjectMapper());
    }
}
