/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Verify
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twilio.rest.verify.v2.service;

import com.twilio.base.Creator;
import com.twilio.base.TwilioResponse;
import com.twilio.constant.EnumConstants;
import com.twilio.constant.EnumConstants.ParameterType;
import com.twilio.converter.Promoter;
import com.twilio.converter.Serializer;
import com.twilio.exception.ApiConnectionException;
import com.twilio.exception.ApiException;
import com.twilio.exception.RestException;
import com.twilio.http.HttpMethod;
import com.twilio.http.Request;
import com.twilio.http.Response;
import com.twilio.http.TwilioRestClient;
import com.twilio.rest.Domains;
import com.twilio.type.*;
import java.util.List;

public class WebhookCreator extends Creator<Webhook> {

    private String pathServiceSid;
    private String friendlyName;
    private List<String> eventTypes;
    private String webhookUrl;
    private Webhook.Status status;
    private Webhook.Version version;

    public WebhookCreator(
        final String pathServiceSid,
        final String friendlyName,
        final List<String> eventTypes,
        final String webhookUrl
    ) {
        this.pathServiceSid = pathServiceSid;
        this.friendlyName = friendlyName;
        this.eventTypes = eventTypes;
        this.webhookUrl = webhookUrl;
    }

    public WebhookCreator setFriendlyName(final String friendlyName) {
        this.friendlyName = friendlyName;
        return this;
    }

    public WebhookCreator setEventTypes(final List<String> eventTypes) {
        this.eventTypes = eventTypes;
        return this;
    }

    public WebhookCreator setEventTypes(final String eventTypes) {
        return setEventTypes(Promoter.listOfOne(eventTypes));
    }

    public WebhookCreator setWebhookUrl(final String webhookUrl) {
        this.webhookUrl = webhookUrl;
        return this;
    }

    public WebhookCreator setStatus(final Webhook.Status status) {
        this.status = status;
        return this;
    }

    public WebhookCreator setVersion(final Webhook.Version version) {
        this.version = version;
        return this;
    }

    private Response makeRequest(final TwilioRestClient client) {
        String path = "/v2/Services/{ServiceSid}/Webhooks";

        path =
            path.replace(
                "{" + "ServiceSid" + "}",
                this.pathServiceSid.toString()
            );

        Request request = new Request(
            HttpMethod.POST,
            Domains.VERIFY.toString(),
            path
        );
        request.setContentType(EnumConstants.ContentType.FORM_URLENCODED);
        addPostParams(request);

        Response response = client.request(request);

        if (response == null) {
            throw new ApiConnectionException(
                "Webhook creation failed: Unable to connect to server"
            );
        } else if (!TwilioRestClient.SUCCESS.test(response.getStatusCode())) {
            RestException restException = RestException.fromJson(
                response.getStream(),
                client.getObjectMapper()
            );
            if (restException == null) {
                throw new ApiException(
                    "Server Error, no content",
                    response.getStatusCode()
                );
            }
            throw new ApiException(restException);
        }
        return response;
    }

    @Override
    public Webhook create(final TwilioRestClient client) {
        Response response = makeRequest(client);
        return Webhook.fromJson(response.getStream(), client.getObjectMapper());
    }

    @Override
    public TwilioResponse<Webhook> createWithResponse(
        final TwilioRestClient client
    ) {
        Response response = makeRequest(client);
        Webhook content = Webhook.fromJson(
            response.getStream(),
            client.getObjectMapper()
        );
        return new TwilioResponse<>(
            content,
            response.getStatusCode(),
            response.getHeaders()
        );
    }

    private void addPostParams(final Request request) {
        if (friendlyName != null) {
            Serializer.toString(
                request,
                "FriendlyName",
                friendlyName,
                ParameterType.URLENCODED
            );
        }

        if (eventTypes != null) {
            for (String param : eventTypes) {
                Serializer.toString(
                    request,
                    "EventTypes",
                    param,
                    ParameterType.URLENCODED
                );
            }
        }

        if (webhookUrl != null) {
            Serializer.toString(
                request,
                "WebhookUrl",
                webhookUrl,
                ParameterType.URLENCODED
            );
        }

        if (status != null) {
            Serializer.toString(
                request,
                "Status",
                status,
                ParameterType.URLENCODED
            );
        }

        if (version != null) {
            Serializer.toString(
                request,
                "Version",
                version,
                ParameterType.URLENCODED
            );
        }
    }
}
