/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Assistants
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twilio.rest.assistants.v1;

import com.twilio.base.Reader;
import com.twilio.constant.EnumConstants.ParameterType;
import com.twilio.converter.Serializer;
import com.twilio.exception.ApiConnectionException;
import com.twilio.exception.ApiException;
import com.twilio.exception.RestException;
import com.twilio.http.HttpMethod;
import com.twilio.http.Request;
import com.twilio.http.Response;
import com.twilio.http.TwilioRestClient;
import com.twilio.rest.Domains;


import com.twilio.type.*;
import com.twilio.base.Page;
import com.twilio.base.ResourceSet;

public class KnowledgeReader extends Reader<Knowledge> {

    private String assistantId;
    private Integer pageSize;

    public KnowledgeReader() {
    }


    public KnowledgeReader setAssistantId(final String assistantId) {
        this.assistantId = assistantId;
        return this;
    }


    public KnowledgeReader setPageSize(final Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }


    @Override
    public ResourceSet<Knowledge> read(final TwilioRestClient client) {
        return new ResourceSet<>(this, client, firstPage(client));
    }

    public Page<Knowledge> firstPage(final TwilioRestClient client) {

        String path = "/v1/Knowledge";


        Request request = new Request(
                HttpMethod.GET,
                Domains.ASSISTANTS.toString(),
                path
        );
        addQueryParams(request);

        return pageForRequest(client, request);
    }

    private Page<Knowledge> pageForRequest(final TwilioRestClient client, final Request request) {
        Response response = client.request(request);
        if (response == null) {
            throw new ApiConnectionException("Knowledge read failed: Unable to connect to server");
        } else if (!TwilioRestClient.SUCCESS.test(response.getStatusCode())) {
            RestException restException = RestException.fromJson(
                    response.getStream(),
                    client.getObjectMapper());

            if (restException == null) {
                throw new ApiException("Server Error, no content", response.getStatusCode());
            }
            throw new ApiException(restException);
        }

        return Page.fromJson(
                "knowledge",
                response.getContent(),
                Knowledge.class,
                client.getObjectMapper());
    }

    @Override
    public Page<Knowledge> previousPage(final Page<Knowledge> page, final TwilioRestClient client) {
        Request request = new Request(HttpMethod.GET, page.getPreviousPageUrl(Domains.API.toString()));
        return pageForRequest(client, request);
    }

    @Override
    public Page<Knowledge> nextPage(final Page<Knowledge> page, final TwilioRestClient client) {
        Request request = new Request(HttpMethod.GET, page.getNextPageUrl(Domains.API.toString()));
        return pageForRequest(client, request);
    }

    @Override
    public Page<Knowledge> getPage(final String targetUrl, final TwilioRestClient client) {
        Request request = new Request(HttpMethod.GET, targetUrl);
        return pageForRequest(client, request);
    }

    private void addQueryParams(final Request request) {


        if (assistantId != null) {
            Serializer.toString(request, "AssistantId", assistantId, ParameterType.QUERY);
        }


        if (pageSize != null) {
            Serializer.toString(request, "PageSize", pageSize, ParameterType.QUERY);
        }


    }
}
