/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Studio
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twilio.rest.studio.v1.flow;

import com.twilio.base.Fetcher;
import com.twilio.base.TwilioResponse;
import com.twilio.exception.ApiConnectionException;
import com.twilio.exception.ApiException;
import com.twilio.exception.RestException;
import com.twilio.http.HttpMethod;
import com.twilio.http.Request;
import com.twilio.http.Response;
import com.twilio.http.TwilioRestClient;
import com.twilio.rest.Domains;
import com.twilio.type.*;

public class ExecutionFetcher extends Fetcher<Execution> {

    private String pathFlowSid;
    private String pathSid;

    public ExecutionFetcher(final String pathFlowSid, final String pathSid) {
        this.pathFlowSid = pathFlowSid;
        this.pathSid = pathSid;
    }

    private Response makeRequest(final TwilioRestClient client) {
        String path = "/v1/Flows/{FlowSid}/Executions/{Sid}";

        path = path.replace("{" + "FlowSid" + "}", this.pathFlowSid.toString());
        path = path.replace("{" + "Sid" + "}", this.pathSid.toString());

        Request request = new Request(
            HttpMethod.GET,
            Domains.STUDIO.toString(),
            path
        );

        Response response = client.request(request);

        if (response == null) {
            throw new ApiConnectionException(
                "Execution fetch failed: Unable to connect to server"
            );
        } else if (!TwilioRestClient.SUCCESS.test(response.getStatusCode())) {
            RestException restException = RestException.fromJson(
                response.getStream(),
                client.getObjectMapper()
            );
            if (restException == null) {
                throw new ApiException(
                    "Server Error, no content",
                    response.getStatusCode()
                );
            }
            throw new ApiException(restException);
        }
        return response;
    }

    @Override
    public Execution fetch(final TwilioRestClient client) {
        Response response = makeRequest(client);
        return Execution.fromJson(
            response.getStream(),
            client.getObjectMapper()
        );
    }

    @Override
    public TwilioResponse<Execution> fetchWithResponse(
        final TwilioRestClient client
    ) {
        Response response = makeRequest(client);
        Execution content = Execution.fromJson(
            response.getStream(),
            client.getObjectMapper()
        );
        return new TwilioResponse<>(
            content,
            response.getStatusCode(),
            response.getHeaders()
        );
    }
}
