/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Intelligence
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twilio.rest.intelligence.v2;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.twilio.base.Resource;
import com.twilio.base.Resource;
import com.twilio.converter.Promoter;
import com.twilio.exception.ApiConnectionException;
import com.twilio.exception.ApiException;
import com.twilio.type.*;
import java.io.IOException;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.time.ZonedDateTime;
import java.util.Map;
import java.util.Objects;
import lombok.Getter;
import lombok.ToString;

@JsonIgnoreProperties(ignoreUnknown = true)
@ToString
public class Transcript extends Resource {

    public static TranscriptCreator creator(
        final String serviceSid,
        final Object channel
    ) {
        return new TranscriptCreator(serviceSid, channel);
    }

    public static TranscriptDeleter deleter(final String pathSid) {
        return new TranscriptDeleter(pathSid);
    }

    public static TranscriptFetcher fetcher(final String pathSid) {
        return new TranscriptFetcher(pathSid);
    }

    public static TranscriptReader reader() {
        return new TranscriptReader();
    }

    public enum Status {
        QUEUED("queued"),
        IN_PROGRESS("in-progress"),
        COMPLETED("completed"),
        NEW("new"),
        FAILED("failed"),
        CANCELED("canceled"),
        ERROR("error");

        private final String value;

        private Status(final String value) {
            this.value = value;
        }

        public String toString() {
            return value;
        }

        @JsonCreator
        public static Status forValue(final String value) {
            return Promoter.enumFromString(value, Status.values());
        }
    }

    /**
     * Converts a JSON String into a Transcript object using the provided ObjectMapper.
     *
     * @param json Raw JSON String
     * @param objectMapper Jackson ObjectMapper
     * @return Transcript object represented by the provided JSON
     */
    public static Transcript fromJson(
        final String json,
        final ObjectMapper objectMapper
    ) {
        // Convert all checked exceptions to Runtime
        try {
            return objectMapper.readValue(json, Transcript.class);
        } catch (final JsonMappingException | JsonParseException e) {
            throw new ApiException(e.getMessage(), e);
        } catch (final IOException e) {
            throw new ApiConnectionException(e.getMessage(), e);
        }
    }

    /**
     * Converts a JSON InputStream into a Transcript object using the provided
     * ObjectMapper.
     *
     * @param json Raw JSON InputStream
     * @param objectMapper Jackson ObjectMapper
     * @return Transcript object represented by the provided JSON
     */
    public static Transcript fromJson(
        final InputStream json,
        final ObjectMapper objectMapper
    ) {
        // Convert all checked exceptions to Runtime
        try {
            return objectMapper.readValue(json, Transcript.class);
        } catch (final JsonMappingException | JsonParseException e) {
            throw new ApiException(e.getMessage(), e);
        } catch (final IOException e) {
            throw new ApiConnectionException(e.getMessage(), e);
        }
    }

    public static String toJson(Object object, ObjectMapper mapper) {
        try {
            return mapper.writeValueAsString(object);
        } catch (final JsonMappingException e) {
            throw new ApiException(e.getMessage(), e);
        } catch (JsonProcessingException e) {
            throw new ApiException(e.getMessage(), e);
        } catch (final IOException e) {
            throw new ApiConnectionException(e.getMessage(), e);
        }
    }

    @Getter
    private final String accountSid;

    @Getter
    private final Object channel;

    @Getter
    private final String customerKey;

    @Getter
    private final Boolean dataLogging;

    @Getter
    private final ZonedDateTime dateCreated;

    @Getter
    private final ZonedDateTime dateUpdated;

    @Getter
    private final Integer duration;

    @Getter
    private final String encryptionCredentialSid;

    @Getter
    private final String languageCode;

    @Getter
    private final Map<String, String> links;

    @Getter
    private final ZonedDateTime mediaStartTime;

    @Getter
    private final Boolean redaction;

    @Getter
    private final String serviceSid;

    @Getter
    private final String sid;

    @Getter
    private final Transcript.Status status;

    @Getter
    private final URI url;

    @JsonCreator
    private Transcript(
        @JsonProperty("account_sid") final String accountSid,
        @JsonProperty("channel") final Object channel,
        @JsonProperty("customer_key") final String customerKey,
        @JsonProperty("data_logging") final Boolean dataLogging,
        @JsonProperty("date_created") @JsonDeserialize(
            using = com.twilio.converter.ISO8601Deserializer.class
        ) final ZonedDateTime dateCreated,
        @JsonProperty("date_updated") @JsonDeserialize(
            using = com.twilio.converter.ISO8601Deserializer.class
        ) final ZonedDateTime dateUpdated,
        @JsonProperty("duration") final Integer duration,
        @JsonProperty(
            "encryption_credential_sid"
        ) final String encryptionCredentialSid,
        @JsonProperty("language_code") final String languageCode,
        @JsonProperty("links") final Map<String, String> links,
        @JsonProperty("media_start_time") @JsonDeserialize(
            using = com.twilio.converter.ISO8601Deserializer.class
        ) final ZonedDateTime mediaStartTime,
        @JsonProperty("redaction") final Boolean redaction,
        @JsonProperty("service_sid") final String serviceSid,
        @JsonProperty("sid") final String sid,
        @JsonProperty("status") final Transcript.Status status,
        @JsonProperty("url") final URI url
    ) {
        this.accountSid = accountSid;
        this.channel = channel;
        this.customerKey = customerKey;
        this.dataLogging = dataLogging;
        this.dateCreated = dateCreated;
        this.dateUpdated = dateUpdated;
        this.duration = duration;
        this.encryptionCredentialSid = encryptionCredentialSid;
        this.languageCode = languageCode;
        this.links = links;
        this.mediaStartTime = mediaStartTime;
        this.redaction = redaction;
        this.serviceSid = serviceSid;
        this.sid = sid;
        this.status = status;
        this.url = url;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }

        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        Transcript other = (Transcript) o;
        return (
            Objects.equals(accountSid, other.accountSid) &&
            Objects.equals(channel, other.channel) &&
            Objects.equals(customerKey, other.customerKey) &&
            Objects.equals(dataLogging, other.dataLogging) &&
            Objects.equals(dateCreated, other.dateCreated) &&
            Objects.equals(dateUpdated, other.dateUpdated) &&
            Objects.equals(duration, other.duration) &&
            Objects.equals(
                encryptionCredentialSid,
                other.encryptionCredentialSid
            ) &&
            Objects.equals(languageCode, other.languageCode) &&
            Objects.equals(links, other.links) &&
            Objects.equals(mediaStartTime, other.mediaStartTime) &&
            Objects.equals(redaction, other.redaction) &&
            Objects.equals(serviceSid, other.serviceSid) &&
            Objects.equals(sid, other.sid) &&
            Objects.equals(status, other.status) &&
            Objects.equals(url, other.url)
        );
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            accountSid,
            channel,
            customerKey,
            dataLogging,
            dateCreated,
            dateUpdated,
            duration,
            encryptionCredentialSid,
            languageCode,
            links,
            mediaStartTime,
            redaction,
            serviceSid,
            sid,
            status,
            url
        );
    }
}
