/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio Memory API
 * APIs for managing memory stores, profiles, events, and conversational intelligence capabilities.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twilio.rest.memory.v1;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.twilio.base.Creator;
import com.twilio.base.TwilioResponse;
import com.twilio.constant.EnumConstants;
import com.twilio.constant.EnumConstants.ParameterType;
import com.twilio.converter.Serializer;
import com.twilio.exception.ApiConnectionException;
import com.twilio.exception.ApiException;
import com.twilio.exception.RestException;
import com.twilio.http.HttpMethod;
import com.twilio.http.Request;
import com.twilio.http.Response;
import com.twilio.http.TwilioRestClient;
import com.twilio.rest.Domains;
import com.twilio.type.*;
import java.io.InputStream;

public class ObservationCreator
    extends Creator<Observation.CreateObservationResponse> {

    private String pathStoreId;
    private String pathProfileId;
    private String acceptEncoding;
    private Observation.ContentEncoding contentEncoding;
    private Observation.CreateObservationsRequest createObservationsRequest;

    public ObservationCreator(
        final String pathStoreId,
        final String pathProfileId,
        final Observation.CreateObservationsRequest createObservationsRequest
    ) {
        this.pathStoreId = pathStoreId;
        this.pathProfileId = pathProfileId;
        this.createObservationsRequest = createObservationsRequest;
    }

    public ObservationCreator setCreateObservationsRequest(
        final Observation.CreateObservationsRequest createObservationsRequest
    ) {
        this.createObservationsRequest = createObservationsRequest;
        return this;
    }

    public ObservationCreator setAcceptEncoding(final String acceptEncoding) {
        this.acceptEncoding = acceptEncoding;
        return this;
    }

    public ObservationCreator setContentEncoding(
        final Observation.ContentEncoding contentEncoding
    ) {
        this.contentEncoding = contentEncoding;
        return this;
    }

    private Response makeRequest(final TwilioRestClient client) {
        String path = "/v1/Stores/{storeId}/Profiles/{profileId}/Observations";

        path = path.replace("{" + "storeId" + "}", this.pathStoreId.toString());
        path =
            path.replace(
                "{" + "profileId" + "}",
                this.pathProfileId.toString()
            );

        Request request = new Request(
            HttpMethod.POST,
            Domains.MEMORY.toString(),
            path
        );
        request.setContentType(EnumConstants.ContentType.JSON);
        addHeaderParams(request);
        addPostParams(request, client);

        Response response = client.request(request);

        if (response == null) {
            throw new ApiConnectionException(
                "Observation creation failed: Unable to connect to server"
            );
        } else if (!TwilioRestClient.SUCCESS.test(response.getStatusCode())) {
            InputStream inputStream = response.getStream();
            RestException restException = RestException.fromJson(
                inputStream,
                client.getObjectMapper()
            );
            if (restException == null) {
                throw new ApiException(
                    "Server Error, no content",
                    response.getStatusCode()
                );
            }
            throw new ApiException(restException);
        }
        return response;
    }

    @Override
    public Observation.CreateObservationResponse create(
        final TwilioRestClient client
    ) {
        Response response = makeRequest(client);
        return Observation.CreateObservationResponse.fromJson(
            response.getStream(),
            client.getObjectMapper()
        );
    }

    @Override
    public TwilioResponse<
        Observation.CreateObservationResponse
    > createWithResponse(final TwilioRestClient client) {
        Response response = makeRequest(client);
        Observation.CreateObservationResponse content =
            Observation.CreateObservationResponse.fromJson(
                response.getStream(),
                client.getObjectMapper()
            );
        return new TwilioResponse<>(
            content,
            response.getStatusCode(),
            response.getHeaders()
        );
    }

    private void addHeaderParams(final Request request) {
        if (acceptEncoding != null) {
            Serializer.toString(
                request,
                "Accept-Encoding",
                acceptEncoding,
                ParameterType.HEADER
            );
        }

        if (contentEncoding != null) {
            Serializer.toString(
                request,
                "Content-Encoding",
                contentEncoding,
                ParameterType.HEADER
            );
        }
    }

    private void addPostParams(final Request request, TwilioRestClient client) {
        ObjectMapper objectMapper = client.getObjectMapper();
        if (createObservationsRequest != null) {
            request.setBody(
                Observation.toJson(createObservationsRequest, objectMapper)
            );
        }
    }
}
