/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio Memory API
 * APIs for managing memory stores, profiles, events, and conversational intelligence capabilities.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twilio.rest.memory.v1;

import com.twilio.base.Page;
import com.twilio.base.Reader;
import com.twilio.base.ResourceSet;
import com.twilio.base.ResourceSetResponse;
import com.twilio.base.TokenPaginationPage;
import com.twilio.base.TwilioResponse;
import com.twilio.constant.EnumConstants.ParameterType;
import com.twilio.converter.Serializer;
import com.twilio.exception.ApiConnectionException;
import com.twilio.exception.ApiException;
import com.twilio.exception.RestException;
import com.twilio.exception.RestStandardException;
import com.twilio.http.HttpMethod;
import com.twilio.http.HttpUtility;
import com.twilio.http.Request;
import com.twilio.http.Response;
import com.twilio.http.TwilioRestClient;
import com.twilio.rest.Domains;
import com.twilio.type.*;
import java.io.InputStream;

public class TraitReader extends Reader<Trait.ListTraitResponse> {

    private String pathStoreId;
    private String pathProfileId;
    private Integer pageSize;
    private String pageToken;
    private Trait.OrderBy orderBy;
    private String traitGroups;

    public TraitReader(final String pathStoreId, final String pathProfileId) {
        this.pathStoreId = pathStoreId;
        this.pathProfileId = pathProfileId;
    }

    public TraitReader setPageSize(final Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    public TraitReader setPageToken(final String pageToken) {
        this.pageToken = pageToken;
        return this;
    }

    public TraitReader setOrderBy(final Trait.OrderBy orderBy) {
        this.orderBy = orderBy;
        return this;
    }

    public TraitReader setTraitGroups(final String traitGroups) {
        this.traitGroups = traitGroups;
        return this;
    }

    public ResourceSetResponse<Trait.ListTraitResponse> readWithResponse(
        final TwilioRestClient client
    ) {
        Request request = buildFirstPageRequest(client);
        Response response = makeRequest(client, request);
        Page<Trait.ListTraitResponse> page = Page.fromJson(
            "traits",
            response.getContent(),
            Trait.ListTraitResponse.class,
            client.getObjectMapper()
        );
        ResourceSet<Trait.ListTraitResponse> resourceSet = new ResourceSet<>(
            this,
            client,
            page
        );
        return new ResourceSetResponse<>(
            resourceSet,
            response.getStatusCode(),
            response.getHeaders()
        );
    }

    private Request buildFirstPageRequest(final TwilioRestClient client) {
        String path = "/v1/Stores/{storeId}/Profiles/{profileId}/Traits";

        path = path.replace("{" + "storeId" + "}", this.pathStoreId.toString());
        path =
            path.replace(
                "{" + "profileId" + "}",
                this.pathProfileId.toString()
            );

        Request request = new Request(
            HttpMethod.GET,
            Domains.MEMORY.toString(),
            path
        );
        addQueryParams(request);
        return request;
    }

    @Override
    public ResourceSet<Trait.ListTraitResponse> read(
        final TwilioRestClient client
    ) {
        return new ResourceSet<>(this, client, firstPage(client));
    }

    public Page<Trait.ListTraitResponse> firstPage(
        final TwilioRestClient client
    ) {
        Request request = buildFirstPageRequest(client);
        return pageForRequest(client, request);
    }

    public TwilioResponse<Page<Trait.ListTraitResponse>> firstPageWithResponse(
        final TwilioRestClient client
    ) {
        Request request = buildFirstPageRequest(client);
        Response response = makeRequest(client, request);
        Page<Trait.ListTraitResponse> page = Page.fromJson(
            "traits",
            response.getContent(),
            Trait.ListTraitResponse.class,
            client.getObjectMapper()
        );
        return new TwilioResponse<>(
            page,
            response.getStatusCode(),
            response.getHeaders()
        );
    }

    private Response makeRequest(
        final TwilioRestClient client,
        final Request request
    ) {
        Response response = client.request(request);
        if (response == null) {
            throw new ApiConnectionException(
                "Trait read failed: Unable to connect to server"
            );
        } else if (!TwilioRestClient.SUCCESS.test(response.getStatusCode())) {
            InputStream inputStream = response.getStream();
            RestStandardException standardException =
                RestStandardException.fromJson(
                    inputStream,
                    client.getObjectMapper()
                );
            if (
                standardException != null && standardException.getType() != null
            ) {
                throw new ApiException(standardException);
            }
            RestException restException = RestException.fromJson(
                inputStream,
                client.getObjectMapper()
            );

            if (restException == null) {
                throw new ApiException(
                    "Server Error, no content",
                    response.getStatusCode()
                );
            }
            throw new ApiException(restException);
        }
        return response;
    }

    private Page<Trait.ListTraitResponse> pageForRequest(
        final TwilioRestClient client,
        final Request request
    ) {
        Response response = makeRequest(client, request);
        return TokenPaginationPage.fromJson(
            "traits",
            response.getContent(),
            Trait.ListTraitResponse.class,
            client.getObjectMapper()
        );
    }

    @Override
    public Page<Trait.ListTraitResponse> previousPage(
        final Page<Trait.ListTraitResponse> page,
        final TwilioRestClient client
    ) {
        String path = "/v1/Stores/{storeId}/Profiles/{profileId}/Traits";

        path = path.replace("{" + "storeId" + "}", this.pathStoreId.toString());
        path =
            path.replace(
                "{" + "profileId" + "}",
                this.pathProfileId.toString()
            );

        path = path + page.previousQueryString();
        Request request = new Request(
            HttpMethod.GET,
            Domains.MEMORY.toString(),
            path
        );

        return pageForRequest(client, request);
    }

    @Override
    public Page<Trait.ListTraitResponse> nextPage(
        final Page<Trait.ListTraitResponse> page,
        final TwilioRestClient client
    ) {
        String path = "/v1/Stores/{storeId}/Profiles/{profileId}/Traits";

        path = path.replace("{" + "storeId" + "}", this.pathStoreId.toString());
        path =
            path.replace(
                "{" + "profileId" + "}",
                this.pathProfileId.toString()
            );

        path = path + page.nextQueryString();
        Request request = new Request(
            HttpMethod.GET,
            Domains.MEMORY.toString(),
            path
        );

        return pageForRequest(client, request);
    }

    @Override
    public Page<Trait.ListTraitResponse> getPage(
        final String targetUrl,
        final TwilioRestClient client
    ) {
        if (!com.twilio.http.HttpUtility.isValidTwilioUrl(targetUrl)) {
            throw new ApiException(
                "Invalid URL: URL must be a valid Twilio domain"
            );
        }
        Request request = new Request(HttpMethod.GET, targetUrl);
        return pageForRequest(client, request);
    }

    private void addQueryParams(final Request request) {
        if (pageSize != null) {
            Serializer.toString(
                request,
                "pageSize",
                pageSize,
                ParameterType.QUERY
            );
        }

        if (pageToken != null) {
            Serializer.toString(
                request,
                "pageToken",
                pageToken,
                ParameterType.QUERY
            );
        }

        if (orderBy != null) {
            Serializer.toString(
                request,
                "orderBy",
                orderBy,
                ParameterType.QUERY
            );
        }

        if (traitGroups != null) {
            Serializer.toString(
                request,
                "traitGroups",
                traitGroups,
                ParameterType.QUERY
            );
        }

        if (getPageSize() != null) {
            request.addQueryParam("PageSize", Integer.toString(getPageSize()));
        }
    }
}
