/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Wireless
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twilio.rest.wireless.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.twilio.base.Resource;
import com.twilio.base.Resource;
import com.twilio.converter.Promoter;
import com.twilio.exception.ApiConnectionException;
import com.twilio.exception.ApiException;
import com.twilio.http.HttpMethod;
import com.twilio.type.*;
import java.io.IOException;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.time.ZonedDateTime;
import java.util.Map;
import java.util.Objects;
import lombok.Getter;
import lombok.ToString;

@JsonIgnoreProperties(ignoreUnknown = true)
@ToString
public class Sim extends Resource {

    public static SimDeleter deleter(final String pathSid) {
        return new SimDeleter(pathSid);
    }

    public static SimFetcher fetcher(final String pathSid) {
        return new SimFetcher(pathSid);
    }

    public static SimReader reader() {
        return new SimReader();
    }

    public static SimUpdater updater(final String pathSid) {
        return new SimUpdater(pathSid);
    }

    public enum Status {
        NEW("new"),
        READY("ready"),
        ACTIVE("active"),
        SUSPENDED("suspended"),
        DEACTIVATED("deactivated"),
        CANCELED("canceled"),
        SCHEDULED("scheduled"),
        UPDATING("updating");

        private final String value;

        private Status(final String value) {
            this.value = value;
        }

        public String toString() {
            return value;
        }

        @JsonCreator
        public static Status forValue(final String value) {
            return Promoter.enumFromString(value, Status.values());
        }
    }

    public enum ResetStatus {
        RESETTING("resetting");

        private final String value;

        private ResetStatus(final String value) {
            this.value = value;
        }

        public String toString() {
            return value;
        }

        @JsonCreator
        public static ResetStatus forValue(final String value) {
            return Promoter.enumFromString(value, ResetStatus.values());
        }
    }

    /**
     * Converts a JSON String into a Sim object using the provided ObjectMapper.
     *
     * @param json Raw JSON String
     * @param objectMapper Jackson ObjectMapper
     * @return Sim object represented by the provided JSON
     */
    public static Sim fromJson(
        final String json,
        final ObjectMapper objectMapper
    ) {
        // Convert all checked exceptions to Runtime
        try {
            return objectMapper.readValue(json, Sim.class);
        } catch (final JsonMappingException | JsonParseException e) {
            throw new ApiException(e.getMessage(), e);
        } catch (final IOException e) {
            throw new ApiConnectionException(e.getMessage(), e);
        }
    }

    /**
     * Converts a JSON InputStream into a Sim object using the provided
     * ObjectMapper.
     *
     * @param json Raw JSON InputStream
     * @param objectMapper Jackson ObjectMapper
     * @return Sim object represented by the provided JSON
     */
    public static Sim fromJson(
        final InputStream json,
        final ObjectMapper objectMapper
    ) {
        // Convert all checked exceptions to Runtime
        try {
            return objectMapper.readValue(json, Sim.class);
        } catch (final JsonMappingException | JsonParseException e) {
            throw new ApiException(e.getMessage(), e);
        } catch (final IOException e) {
            throw new ApiConnectionException(e.getMessage(), e);
        }
    }

    public static String toJson(Object object, ObjectMapper mapper) {
        try {
            return mapper.writeValueAsString(object);
        } catch (final JsonMappingException e) {
            throw new ApiException(e.getMessage(), e);
        } catch (JsonProcessingException e) {
            throw new ApiException(e.getMessage(), e);
        } catch (final IOException e) {
            throw new ApiConnectionException(e.getMessage(), e);
        }
    }

    @Getter
    private final String accountSid;

    @Getter
    private final HttpMethod commandsCallbackMethod;

    @Getter
    private final URI commandsCallbackUrl;

    @Getter
    private final ZonedDateTime dateCreated;

    @Getter
    private final ZonedDateTime dateUpdated;

    @Getter
    private final String eId;

    @Getter
    private final String friendlyName;

    @Getter
    private final String iccid;

    @Getter
    private final String ipAddress;

    @Getter
    private final Map<String, String> links;

    @Getter
    private final String ratePlanSid;

    @Getter
    private final Sim.ResetStatus resetStatus;

    @Getter
    private final String sid;

    @Getter
    private final HttpMethod smsFallbackMethod;

    @Getter
    private final URI smsFallbackUrl;

    @Getter
    private final HttpMethod smsMethod;

    @Getter
    private final URI smsUrl;

    @Getter
    private final Sim.Status status;

    @Getter
    private final String uniqueName;

    @Getter
    private final URI url;

    @Getter
    private final HttpMethod voiceFallbackMethod;

    @Getter
    private final URI voiceFallbackUrl;

    @Getter
    private final HttpMethod voiceMethod;

    @Getter
    private final URI voiceUrl;

    @JsonCreator
    private Sim(
        @JsonProperty("account_sid") final String accountSid,
        @JsonProperty(
            "commands_callback_method"
        ) final HttpMethod commandsCallbackMethod,
        @JsonProperty("commands_callback_url") final URI commandsCallbackUrl,
        @JsonProperty("date_created") @JsonDeserialize(
            using = com.twilio.converter.ISO8601Deserializer.class
        ) final ZonedDateTime dateCreated,
        @JsonProperty("date_updated") @JsonDeserialize(
            using = com.twilio.converter.ISO8601Deserializer.class
        ) final ZonedDateTime dateUpdated,
        @JsonProperty("e_id") final String eId,
        @JsonProperty("friendly_name") final String friendlyName,
        @JsonProperty("iccid") final String iccid,
        @JsonProperty("ip_address") final String ipAddress,
        @JsonProperty("links") final Map<String, String> links,
        @JsonProperty("rate_plan_sid") final String ratePlanSid,
        @JsonProperty("reset_status") final Sim.ResetStatus resetStatus,
        @JsonProperty("sid") final String sid,
        @JsonProperty("sms_fallback_method") final HttpMethod smsFallbackMethod,
        @JsonProperty("sms_fallback_url") final URI smsFallbackUrl,
        @JsonProperty("sms_method") final HttpMethod smsMethod,
        @JsonProperty("sms_url") final URI smsUrl,
        @JsonProperty("status") final Sim.Status status,
        @JsonProperty("unique_name") final String uniqueName,
        @JsonProperty("url") final URI url,
        @JsonProperty(
            "voice_fallback_method"
        ) final HttpMethod voiceFallbackMethod,
        @JsonProperty("voice_fallback_url") final URI voiceFallbackUrl,
        @JsonProperty("voice_method") final HttpMethod voiceMethod,
        @JsonProperty("voice_url") final URI voiceUrl
    ) {
        this.accountSid = accountSid;
        this.commandsCallbackMethod = commandsCallbackMethod;
        this.commandsCallbackUrl = commandsCallbackUrl;
        this.dateCreated = dateCreated;
        this.dateUpdated = dateUpdated;
        this.eId = eId;
        this.friendlyName = friendlyName;
        this.iccid = iccid;
        this.ipAddress = ipAddress;
        this.links = links;
        this.ratePlanSid = ratePlanSid;
        this.resetStatus = resetStatus;
        this.sid = sid;
        this.smsFallbackMethod = smsFallbackMethod;
        this.smsFallbackUrl = smsFallbackUrl;
        this.smsMethod = smsMethod;
        this.smsUrl = smsUrl;
        this.status = status;
        this.uniqueName = uniqueName;
        this.url = url;
        this.voiceFallbackMethod = voiceFallbackMethod;
        this.voiceFallbackUrl = voiceFallbackUrl;
        this.voiceMethod = voiceMethod;
        this.voiceUrl = voiceUrl;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }

        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        Sim other = (Sim) o;
        return (
            Objects.equals(accountSid, other.accountSid) &&
            Objects.equals(
                commandsCallbackMethod,
                other.commandsCallbackMethod
            ) &&
            Objects.equals(commandsCallbackUrl, other.commandsCallbackUrl) &&
            Objects.equals(dateCreated, other.dateCreated) &&
            Objects.equals(dateUpdated, other.dateUpdated) &&
            Objects.equals(eId, other.eId) &&
            Objects.equals(friendlyName, other.friendlyName) &&
            Objects.equals(iccid, other.iccid) &&
            Objects.equals(ipAddress, other.ipAddress) &&
            Objects.equals(links, other.links) &&
            Objects.equals(ratePlanSid, other.ratePlanSid) &&
            Objects.equals(resetStatus, other.resetStatus) &&
            Objects.equals(sid, other.sid) &&
            Objects.equals(smsFallbackMethod, other.smsFallbackMethod) &&
            Objects.equals(smsFallbackUrl, other.smsFallbackUrl) &&
            Objects.equals(smsMethod, other.smsMethod) &&
            Objects.equals(smsUrl, other.smsUrl) &&
            Objects.equals(status, other.status) &&
            Objects.equals(uniqueName, other.uniqueName) &&
            Objects.equals(url, other.url) &&
            Objects.equals(voiceFallbackMethod, other.voiceFallbackMethod) &&
            Objects.equals(voiceFallbackUrl, other.voiceFallbackUrl) &&
            Objects.equals(voiceMethod, other.voiceMethod) &&
            Objects.equals(voiceUrl, other.voiceUrl)
        );
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            accountSid,
            commandsCallbackMethod,
            commandsCallbackUrl,
            dateCreated,
            dateUpdated,
            eId,
            friendlyName,
            iccid,
            ipAddress,
            links,
            ratePlanSid,
            resetStatus,
            sid,
            smsFallbackMethod,
            smsFallbackUrl,
            smsMethod,
            smsUrl,
            status,
            uniqueName,
            url,
            voiceFallbackMethod,
            voiceFallbackUrl,
            voiceMethod,
            voiceUrl
        );
    }
}
