/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Content
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twilio.rest.content.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.twilio.base.Resource;
import com.twilio.base.Resource;
import com.twilio.exception.ApiConnectionException;
import com.twilio.exception.ApiException;
import com.twilio.type.*;
import java.io.IOException;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.time.ZonedDateTime;
import java.util.Objects;
import lombok.Getter;
import lombok.ToString;

@JsonIgnoreProperties(ignoreUnknown = true)
@ToString
public class LegacyContent extends Resource {

    public static LegacyContentReader reader() {
        return new LegacyContentReader();
    }

    /**
     * Converts a JSON String into a LegacyContent object using the provided ObjectMapper.
     *
     * @param json Raw JSON String
     * @param objectMapper Jackson ObjectMapper
     * @return LegacyContent object represented by the provided JSON
     */
    public static LegacyContent fromJson(
        final String json,
        final ObjectMapper objectMapper
    ) {
        // Convert all checked exceptions to Runtime
        try {
            return objectMapper.readValue(json, LegacyContent.class);
        } catch (final JsonMappingException | JsonParseException e) {
            throw new ApiException(e.getMessage(), e);
        } catch (final IOException e) {
            throw new ApiConnectionException(e.getMessage(), e);
        }
    }

    /**
     * Converts a JSON InputStream into a LegacyContent object using the provided
     * ObjectMapper.
     *
     * @param json Raw JSON InputStream
     * @param objectMapper Jackson ObjectMapper
     * @return LegacyContent object represented by the provided JSON
     */
    public static LegacyContent fromJson(
        final InputStream json,
        final ObjectMapper objectMapper
    ) {
        // Convert all checked exceptions to Runtime
        try {
            return objectMapper.readValue(json, LegacyContent.class);
        } catch (final JsonMappingException | JsonParseException e) {
            throw new ApiException(e.getMessage(), e);
        } catch (final IOException e) {
            throw new ApiConnectionException(e.getMessage(), e);
        }
    }

    public static String toJson(Object object, ObjectMapper mapper) {
        try {
            return mapper.writeValueAsString(object);
        } catch (final JsonMappingException e) {
            throw new ApiException(e.getMessage(), e);
        } catch (JsonProcessingException e) {
            throw new ApiException(e.getMessage(), e);
        } catch (final IOException e) {
            throw new ApiConnectionException(e.getMessage(), e);
        }
    }

    @Getter
    private final String accountSid;

    @Getter
    private final ZonedDateTime dateCreated;

    @Getter
    private final ZonedDateTime dateUpdated;

    @Getter
    private final String friendlyName;

    @Getter
    private final String language;

    @Getter
    private final String legacyBody;

    @Getter
    private final String legacyTemplateName;

    @Getter
    private final String sid;

    @Getter
    private final Object types;

    @Getter
    private final URI url;

    @Getter
    private final Object variables;

    @JsonCreator
    private LegacyContent(
        @JsonProperty("account_sid") final String accountSid,
        @JsonProperty("date_created") @JsonDeserialize(
            using = com.twilio.converter.ISO8601Deserializer.class
        ) final ZonedDateTime dateCreated,
        @JsonProperty("date_updated") @JsonDeserialize(
            using = com.twilio.converter.ISO8601Deserializer.class
        ) final ZonedDateTime dateUpdated,
        @JsonProperty("friendly_name") final String friendlyName,
        @JsonProperty("language") final String language,
        @JsonProperty("legacy_body") final String legacyBody,
        @JsonProperty("legacy_template_name") final String legacyTemplateName,
        @JsonProperty("sid") final String sid,
        @JsonProperty("types") final Object types,
        @JsonProperty("url") final URI url,
        @JsonProperty("variables") final Object variables
    ) {
        this.accountSid = accountSid;
        this.dateCreated = dateCreated;
        this.dateUpdated = dateUpdated;
        this.friendlyName = friendlyName;
        this.language = language;
        this.legacyBody = legacyBody;
        this.legacyTemplateName = legacyTemplateName;
        this.sid = sid;
        this.types = types;
        this.url = url;
        this.variables = variables;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }

        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        LegacyContent other = (LegacyContent) o;
        return (
            Objects.equals(accountSid, other.accountSid) &&
            Objects.equals(dateCreated, other.dateCreated) &&
            Objects.equals(dateUpdated, other.dateUpdated) &&
            Objects.equals(friendlyName, other.friendlyName) &&
            Objects.equals(language, other.language) &&
            Objects.equals(legacyBody, other.legacyBody) &&
            Objects.equals(legacyTemplateName, other.legacyTemplateName) &&
            Objects.equals(sid, other.sid) &&
            Objects.equals(types, other.types) &&
            Objects.equals(url, other.url) &&
            Objects.equals(variables, other.variables)
        );
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            accountSid,
            dateCreated,
            dateUpdated,
            friendlyName,
            language,
            legacyBody,
            legacyTemplateName,
            sid,
            types,
            url,
            variables
        );
    }
}
