/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Studio
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twilio.rest.studio.v2;

import com.twilio.base.TwilioResponse;
import com.twilio.base.Updater;
import com.twilio.constant.EnumConstants;
import com.twilio.constant.EnumConstants.ParameterType;
import com.twilio.converter.Serializer;
import com.twilio.exception.ApiConnectionException;
import com.twilio.exception.ApiException;
import com.twilio.exception.RestException;
import com.twilio.http.HttpMethod;
import com.twilio.http.Request;
import com.twilio.http.Response;
import com.twilio.http.TwilioRestClient;
import com.twilio.rest.Domains;
import com.twilio.type.*;

public class FlowUpdater extends Updater<Flow> {

    private String pathSid;
    private Flow.Status status;
    private String friendlyName;
    private Object definition;
    private String commitMessage;

    public FlowUpdater(final String pathSid, final Flow.Status status) {
        this.pathSid = pathSid;
        this.status = status;
    }

    public FlowUpdater setStatus(final Flow.Status status) {
        this.status = status;
        return this;
    }

    public FlowUpdater setFriendlyName(final String friendlyName) {
        this.friendlyName = friendlyName;
        return this;
    }

    public FlowUpdater setDefinition(final Object definition) {
        this.definition = definition;
        return this;
    }

    public FlowUpdater setCommitMessage(final String commitMessage) {
        this.commitMessage = commitMessage;
        return this;
    }

    private Response makeRequest(final TwilioRestClient client) {
        String path = "/v2/Flows/{Sid}";

        path = path.replace("{" + "Sid" + "}", this.pathSid.toString());

        Request request = new Request(
            HttpMethod.POST,
            Domains.STUDIO.toString(),
            path
        );
        request.setContentType(EnumConstants.ContentType.FORM_URLENCODED);
        addPostParams(request);

        Response response = client.request(request);

        if (response == null) {
            throw new ApiConnectionException(
                "Flow update failed: Unable to connect to server"
            );
        } else if (!TwilioRestClient.SUCCESS.test(response.getStatusCode())) {
            RestException restException = RestException.fromJson(
                response.getStream(),
                client.getObjectMapper()
            );
            if (restException == null) {
                throw new ApiException(
                    "Server Error, no content",
                    response.getStatusCode()
                );
            }
            throw new ApiException(restException);
        }
        return response;
    }

    @Override
    public Flow update(final TwilioRestClient client) {
        Response response = makeRequest(client);
        return Flow.fromJson(response.getStream(), client.getObjectMapper());
    }

    @Override
    public TwilioResponse<Flow> updateWithResponse(
        final TwilioRestClient client
    ) {
        Response response = makeRequest(client);
        Flow content = Flow.fromJson(
            response.getStream(),
            client.getObjectMapper()
        );
        return new TwilioResponse<>(
            content,
            response.getStatusCode(),
            response.getHeaders()
        );
    }

    private void addPostParams(final Request request) {
        if (status != null) {
            Serializer.toString(
                request,
                "Status",
                status,
                ParameterType.URLENCODED
            );
        }

        if (friendlyName != null) {
            Serializer.toString(
                request,
                "FriendlyName",
                friendlyName,
                ParameterType.URLENCODED
            );
        }

        if (definition != null) {
            Serializer.toString(
                request,
                "Definition",
                definition,
                ParameterType.URLENCODED
            );
        }

        if (commitMessage != null) {
            Serializer.toString(
                request,
                "CommitMessage",
                commitMessage,
                ParameterType.URLENCODED
            );
        }
    }
}
