/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */

package com.twilio.rest.preview.understand;

import com.twilio.base.Creator;
import com.twilio.converter.Promoter;
import com.twilio.exception.ApiConnectionException;
import com.twilio.exception.ApiException;
import com.twilio.exception.RestException;
import com.twilio.http.HttpMethod;
import com.twilio.http.Request;
import com.twilio.http.Response;
import com.twilio.http.TwilioRestClient;
import com.twilio.rest.Domains;

import java.net.URI;

/**
 * PLEASE NOTE that this class contains preview products that are subject to
 * change. Use them with caution. If you currently do not have developer preview
 * access, please contact help@twilio.com.
 */
public class AssistantCreator extends Creator<Assistant> {
    private String friendlyName;
    private Boolean logQueries;
    private Integer ttl;
    private String uniqueName;
    private URI responseUrl;
    private URI callbackUrl;
    private String callbackEvents;

    /**
     * A text description for the Assistant. It is non-unique and can up to 255
     * characters long..
     * 
     * @param friendlyName A text description for the Assistant. It is non-unique
     *                     and can up to 255 characters long.
     * @return this
     */
    public AssistantCreator setFriendlyName(final String friendlyName) {
        this.friendlyName = friendlyName;
        return this;
    }

    /**
     * A boolean that specifies whether queries should be logged for 30 days further
     * training. If false, no queries will be stored, if true, queries will be
     * stored for 30 days and deleted thereafter. Defaults to true if no value is
     * provided..
     * 
     * @param logQueries A boolean that specifies whether queries should be logged
     *                   for 30 days further training. If false, no queries will be
     *                   stored, if true, queries will be stored for 30 days and
     *                   deleted thereafter. Defaults to true if no value is
     *                   provided.
     * @return this
     */
    public AssistantCreator setLogQueries(final Boolean logQueries) {
        this.logQueries = logQueries;
        return this;
    }

    /**
     * The ttl.
     * 
     * @param ttl The ttl
     * @return this
     */
    public AssistantCreator setTtl(final Integer ttl) {
        this.ttl = ttl;
        return this;
    }

    /**
     * A user-provided string that uniquely identifies this resource as an
     * alternative to the sid. Unique up to 64 characters long..
     * 
     * @param uniqueName A user-provided string that uniquely identifies this
     *                   resource as an alternative to the sid. Unique up to 64
     *                   characters long.
     * @return this
     */
    public AssistantCreator setUniqueName(final String uniqueName) {
        this.uniqueName = uniqueName;
        return this;
    }

    /**
     * The webhook URL called to fetch the response to an incoming communication
     * expressed in Assistant TwiML..
     * 
     * @param responseUrl The webhook URL called to fetch the response to an
     *                    incoming communication expressed in Assistant TwiML.
     * @return this
     */
    public AssistantCreator setResponseUrl(final URI responseUrl) {
        this.responseUrl = responseUrl;
        return this;
    }

    /**
     * The webhook URL called to fetch the response to an incoming communication
     * expressed in Assistant TwiML..
     * 
     * @param responseUrl The webhook URL called to fetch the response to an
     *                    incoming communication expressed in Assistant TwiML.
     * @return this
     */
    public AssistantCreator setResponseUrl(final String responseUrl) {
        return setResponseUrl(Promoter.uriFromString(responseUrl));
    }

    /**
     * The callback_url.
     * 
     * @param callbackUrl The callback_url
     * @return this
     */
    public AssistantCreator setCallbackUrl(final URI callbackUrl) {
        this.callbackUrl = callbackUrl;
        return this;
    }

    /**
     * The callback_url.
     * 
     * @param callbackUrl The callback_url
     * @return this
     */
    public AssistantCreator setCallbackUrl(final String callbackUrl) {
        return setCallbackUrl(Promoter.uriFromString(callbackUrl));
    }

    /**
     * The callback_events.
     * 
     * @param callbackEvents The callback_events
     * @return this
     */
    public AssistantCreator setCallbackEvents(final String callbackEvents) {
        this.callbackEvents = callbackEvents;
        return this;
    }

    /**
     * Make the request to the Twilio API to perform the create.
     * 
     * @param client TwilioRestClient with which to make the request
     * @return Created Assistant
     */
    @Override
    @SuppressWarnings("checkstyle:linelength")
    public Assistant create(final TwilioRestClient client) {
        Request request = new Request(
            HttpMethod.POST,
            Domains.PREVIEW.toString(),
            "/understand/Assistants",
            client.getRegion()
        );

        addPostParams(request);
        Response response = client.request(request);

        if (response == null) {
            throw new ApiConnectionException("Assistant creation failed: Unable to connect to server");
        } else if (!TwilioRestClient.SUCCESS.apply(response.getStatusCode())) {
            RestException restException = RestException.fromJson(response.getStream(), client.getObjectMapper());
            if (restException == null) {
                throw new ApiException("Server Error, no content");
            }

            throw new ApiException(
                restException.getMessage(),
                restException.getCode(),
                restException.getMoreInfo(),
                restException.getStatus(),
                null
            );
        }

        return Assistant.fromJson(response.getStream(), client.getObjectMapper());
    }

    /**
     * Add the requested post parameters to the Request.
     * 
     * @param request Request to add post params to
     */
    private void addPostParams(final Request request) {
        if (friendlyName != null) {
            request.addPostParam("FriendlyName", friendlyName);
        }

        if (logQueries != null) {
            request.addPostParam("LogQueries", logQueries.toString());
        }

        if (ttl != null) {
            request.addPostParam("Ttl", ttl.toString());
        }

        if (uniqueName != null) {
            request.addPostParam("UniqueName", uniqueName);
        }

        if (responseUrl != null) {
            request.addPostParam("ResponseUrl", responseUrl.toString());
        }

        if (callbackUrl != null) {
            request.addPostParam("CallbackUrl", callbackUrl.toString());
        }

        if (callbackEvents != null) {
            request.addPostParam("CallbackEvents", callbackEvents);
        }
    }
}