/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio API definition for public-api voice
 * Powers Twilio public-api voice
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twilio.rest.voice.v2;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.twilio.base.TwilioResponse;
import com.twilio.base.Updater;
import com.twilio.constant.EnumConstants;
import com.twilio.exception.ApiConnectionException;
import com.twilio.exception.ApiException;
import com.twilio.exception.RestException;
import com.twilio.http.HttpMethod;
import com.twilio.http.Request;
import com.twilio.http.Response;
import com.twilio.http.TwilioRestClient;
import com.twilio.rest.Domains;
import com.twilio.type.*;
import java.io.InputStream;

public class TypeUpdater extends Updater<Type> {

    private String pathType;
    private String pathIdOrUniqueName;
    private Type.VoiceV2ConfigurationRequest voiceV2ConfigurationRequest;

    public TypeUpdater(final String pathType, final String pathIdOrUniqueName) {
        this.pathType = pathType;
        this.pathIdOrUniqueName = pathIdOrUniqueName;
    }

    public TypeUpdater setVoiceV2ConfigurationRequest(
        final Type.VoiceV2ConfigurationRequest voiceV2ConfigurationRequest
    ) {
        this.voiceV2ConfigurationRequest = voiceV2ConfigurationRequest;
        return this;
    }

    private Response makeRequest(final TwilioRestClient client) {
        String path = "/v2/Configurations/{Type}/{IdOrUniqueName}";

        path = path.replace("{" + "Type" + "}", this.pathType.toString());
        path = path.replace(
            "{" + "IdOrUniqueName" + "}",
            this.pathIdOrUniqueName.toString()
        );

        Request request = new Request(
            HttpMethod.PUT,
            Domains.VOICE.toString(),
            path
        );
        request.setContentType(EnumConstants.ContentType.JSON);
        addPostParams(request, client);

        Response response = client.request(request);

        if (response == null) {
            throw new ApiConnectionException(
                "Type update failed: Unable to connect to server"
            );
        } else if (!TwilioRestClient.SUCCESS.test(response.getStatusCode())) {
            InputStream inputStream = response.getStream();
            RestException restException = RestException.fromJson(
                inputStream,
                client.getObjectMapper()
            );
            if (restException == null) {
                throw new ApiException(
                    "Server Error, no content",
                    response.getStatusCode()
                );
            }
            throw new ApiException(restException);
        }
        return response;
    }

    @Override
    public Type update(final TwilioRestClient client) {
        Response response = makeRequest(client);
        return Type.fromJson(response.getStream(), client.getObjectMapper());
    }

    @Override
    public TwilioResponse<Type> updateWithResponse(
        final TwilioRestClient client
    ) {
        Response response = makeRequest(client);
        Type content = Type.fromJson(
            response.getStream(),
            client.getObjectMapper()
        );
        return new TwilioResponse<>(
            content,
            response.getStatusCode(),
            response.getHeaders()
        );
    }

    private void addPostParams(final Request request, TwilioRestClient client) {
        ObjectMapper objectMapper = client.getObjectMapper();
        if (voiceV2ConfigurationRequest != null) {
            request.setBody(
                Type.toJson(voiceV2ConfigurationRequest, objectMapper)
            );
        }
    }
}
