name: CI
on:
  push:
    branches: ["supplychain-*"]
  pull_request:
    branches: ["supplychain-*"]

jobs:
  build:
    name: Build
    runs-on: ${{ github.event.pull_request.head.repo.fork && 'ubuntu-latest' || 'ubuntu-x64' }}
    environment: test_docker
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 20
    steps:
      - name: Checkout twilio-java
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Set up Java
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "maven"

      - name: Artifactory OIDC
        if: ${{ !github.event.pull_request.head.repo.fork }}
        uses: twilio/sdk-actions/artifactory-oidc@a7170729517a2f173eb3bbd9395ac5fb01e375a8 # java_maven
        with:
          ecosystem: "maven"

      - name: Docker Hub OIDC
        if: ${{ !github.event.pull_request.head.repo.fork }}
        uses: twilio/sdk-actions/dockerhub-oidc@a7170729517a2f173eb3bbd9395ac5fb01e375a8 # java_maven

      - name: Pull Docker image
        if: ${{ !github.event.pull_request.head.repo.fork }}
        # Placeholder for docker build and push — validates Docker Hub OIDC login
        run: docker pull twilio/twilio-java:latest

      - run: mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
