name: Twilio Public release-maven

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-x64
    if: github.repository_owner == 'twilio'
    timeout-minutes: 20
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        java: [11, 17, 21]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Artifactory OIDC
        uses: twilio/sdk-actions/artifactory-oidc@4ffc0c647c8d692a8fff24d4f767b207c3d1222e # java_maven
        with:
          ecosystem: maven

      - name: Set up Java
        uses: actions/setup-java@e9fbacdec3bb3b6036605a3e6f7995d66773a8c6 # v3.14.2
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - run: mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
      - name: Run unit tests
        run: mvn test -B

  deploy:
    name: Publish to Maven Central
    needs: [test]
    runs-on: ubuntu-x64
    if: success() && github.ref_type == 'tag' && github.repository_owner == 'twilio'
    environment:
      name: production
      url: https://central.sonatype.com/artifact/com.twilio.sdk/twilio/${{ github.ref_name }}
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0

      - name: Artifactory OIDC
        uses: twilio/sdk-actions/artifactory-oidc@4ffc0c647c8d692a8fff24d4f767b207c3d1222e # java_maven
        with:
          ecosystem: maven

#      - name: Login to Docker Hub
#        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1 # v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_AUTH_TOKEN }}

      - name: Get tagged version
        run: echo "GITHUB_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: sendgrid/dx-automator/actions/release@08b601b726671445abc798ed59881766ec8fefc6
        with:
          footer: '**[Maven](https://central.sonatype.com/artifact/com.twilio.sdk/twilio/${version})**'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Build and push Docker image
#        run: make docker-build && make docker-push

      - name: Set up Java for Maven Central publish
        uses: actions/setup-java@e9fbacdec3bb3b6036605a3e6f7995d66773a8c6 # v3.14.2
        with:
          java-version: '11'
          distribution: temurin
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - run: mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

      - name: Publish to Maven Central
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: mvn clean deploy -DskipTests=true -B -U -Prelease

      - name: Submit metric to Datadog
        uses: sendgrid/dx-automator/actions/datadog-release-metric@08b601b726671445abc798ed59881766ec8fefc6
        env:
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}

